export default {
  "login": "john-doe",
  "avatar_url": "https://www.sugarsteam.com/images/johndoe.png",
  "html_url": "https://github.com/john-doe",
  "name": "John Doe",
  "company": "John Doe",
  "blog": "www.john-doe.com",
  "location": "John Doe's Home",
  "email": null,
  "bio": "Creator of John Doe",
  "twitter_username": "john_doe",
  "public_repos": 214,
  "public_gists": 0,
  "followers": 5417,
  "following": 0,
  }